import json
import time
from collections.abc import Callable
from typing import Any

import config
from agents.base import BaseAgent
from database import verify_double_entry
from math_engine import calculate_remaining_buffer
from schema import AuditAssessmentPayload, CheckedDecisionPayload

# Import google-genai dynamically if LIVE_GCP mode is active
if config.MODE == "LIVE_GCP":
    from google import genai


class CheckerAgent(BaseAgent):
    def __init__(
        self, event_callback: Callable[[dict[str, Any]], None] | None = None
    ):
        super().__init__(
            name="CheckerAgent",
            role="Risk Manager & LLM Risk Evaluator",
            event_callback=event_callback,
        )

    def run(self, assessment: AuditAssessmentPayload) -> CheckedDecisionPayload:
        start_time = time.perf_counter()
        self.thoughts = []

        self.log_thought("Starting final transaction validation and risk analysis...")
        self.emit_event(
            task="Verifying ledger double-entry and evaluating LLM risk comments",
            status="processing",
        )

        # 1. Perform double-entry validation check
        self.log_thought("Calculating double-entry balances for verification...")

        # Proposed values
        buffer_balance = calculate_remaining_buffer(
            assessment.dlg_pool_limit_inr,
            assessment.ingested_data.cumulative_dlg_payout_inr,
            assessment.ingested_data.current_payout_requested_inr,
        )
        cumulative_payouts = (
            assessment.ingested_data.cumulative_dlg_payout_inr
            + assessment.ingested_data.current_payout_requested_inr
        )
        initial_pool_amount = assessment.dlg_pool_limit_inr

        double_entry_verified = False
        rejection_reasons = []
        final_status = assessment.suggested_status

        try:
            verify_double_entry(
                buffer_balance=buffer_balance,
                cumulative_payouts=cumulative_payouts,
                initial_pool_amount=initial_pool_amount,
            )
            double_entry_verified = True
            self.log_thought("Double-entry verification passed successfully.")
        except ValueError as ve:
            self.log_thought(f"Double-entry validation failed: {ve!s}")
            double_entry_verified = False
            rejection_reasons.append(str(ve))
            final_status = "HELD"  # Checker holds the transaction

        # 2. Integrate Gemini LLM for qualitative risks
        self.log_thought(
            f"Running qualitative risk assessment using Gemini (MODE: {config.MODE})..."
        )
        adversarial_remarks = ""

        if config.MODE == "LIVE_GCP":
            try:
                # Initialize Google GenAI client for Vertex AI
                client = genai.Client(
                    vertexai=True,
                    project=config.GCP_PROJECT,
                    location=config.GCP_LOCATION,
                )

                # Context mapping
                context_data = {
                    "ingested_data": assessment.ingested_data.model_dump(),
                    "dlg_pool_limit_inr": assessment.dlg_pool_limit_inr,
                    "current_dlg_utilization_percentage": assessment.current_dlg_utilization_percentage,
                    "is_cap_exceeded": assessment.is_cap_exceeded,
                    "is_tenure_valid": assessment.is_tenure_valid,
                    "cel_rules_evaluation": assessment.cel_rules_evaluation,
                    "suggested_status": assessment.suggested_status,
                    "violation_reasons": assessment.violation_reasons,
                }

                prompt = (
                    "You are a Senior Risk Officer auditing a Digital Lending Guarantee (DLG) transaction. "
                    "Analyze the following transaction details and compliance assessment for qualitative risks "
                    "such as rapid pool drawdown, portfolio concentration, or structural risks. "
                    "Keep your analysis to a single paragraph. Begin with 'Risk level: LOW/MEDIUM/HIGH'.\n\n"
                    f"Transaction Context:\n{json.dumps(context_data, indent=2)}"
                )

                response = client.models.generate_content(
                    model=config.GEMINI_MODEL, contents=prompt
                )
                adversarial_remarks = response.text or "No remarks generated by Gemini."
                self.log_thought(f"Gemini output: {adversarial_remarks}")

            except Exception as e:  # noqa: BLE001
                self.log_thought(f"Error calling live Gemini client: {e!s}")
                adversarial_remarks = (
                    f"Error during Gemini call: {e!s}. Proceeding with caution."
                )
        else:
            # MOCK mode
            # Simulate network latency
            time.sleep(0.5)

            if final_status == "BLOCKED":
                adversarial_remarks = (
                    "Risk level: HIGH. The transaction violates core statutory guardrails (cap limit exceeded "
                    "or tenure mismatch). Proceeding with this transaction introduces significant compliance risk "
                    "under RBI DLG guidelines."
                )
            elif final_status == "HELD":
                adversarial_remarks = (
                    "Risk level: HIGH. Double-entry validation failure detected. Ledger inconsistency may "
                    "indicate concurrent write conflicts or database synchronization issues."
                )
            else:
                # If utilization is high (e.g. > 80%)
                if assessment.current_dlg_utilization_percentage > 80.0:
                    adversarial_remarks = (
                        "Risk level: MEDIUM. The DLG pool utilization has exceeded 80%. "
                        "Monitor closely for rapid pool drawdown risks and concentration of claims."
                    )
                else:
                    adversarial_remarks = (
                        "Risk level: LOW. No significant qualitative risks identified. "
                        "The transaction aligns with RBI DLG limits and maintains appropriate buffer margins."
                    )
            self.log_thought(f"Simulated Gemini response: {adversarial_remarks}")

        # Combine assessment violations with checker violations
        all_rejections = list(assessment.violation_reasons) + rejection_reasons

        decision = CheckedDecisionPayload(
            audit_assessment=assessment,
            checker_id="Agent-Checker-01",
            double_entry_verified=double_entry_verified,
            final_status=final_status,
            rejection_reasons=all_rejections,
            adversarial_remarks=adversarial_remarks,
        )

        latency_ms = (time.perf_counter() - start_time) * 1000.0
        self.emit_event(
            task="Completed final checker risk audit",
            status="completed",
            results=decision.model_dump(),
            latency_ms=latency_ms,
        )
        return decision
